name: "OZ - Wallet"
main: de.omegazirkel.risingworld.Wallet
version: 0.8.1
author: "Maik 'Devidian' Laschober"
team: "Omega Zirkel"
description: "Wallet and economy state plugin"
license: N/A
website: https://api.github.com/repos/Devidian/rw-plugin-oz-wallet/releases/latest
loadorder: -100
