name: "OZ - Wallet"
main: de.omegazirkel.risingworld.Wallet
version: 0.1.0
author: "Maik 'Devidian' Laschober"
team: "Omega Zirkel"
description: "Wallet and economy state plugin"
license: N/A
website: N/A
loadorder: -100
