package de.omegazirkel.risingworld.wallet;

public enum WalletErrorCode {
    NONE,
    INVALID_ARGUMENT,
    CURRENCY_ALREADY_REGISTERED,
    ACCOUNT_NOT_FOUND,
    ACCOUNT_OWNERSHIP_CONFLICT,
    ACCOUNT_ARCHIVED,
    ACCOUNT_NOT_EMPTY,
    TRANSFER_NOT_FOUND,
    UNKNOWN_CURRENCY,
    INSUFFICIENT_FUNDS,
    IDEMPOTENCY_CONFLICT,
    DATABASE_ERROR
}
