
defaultCurrency.identifier=OZC
defaultCurrency.name=Omega Zirkel Coin
# Other Icons: icon-ki-coin-omega-silver, icon-ki-coin-default
defaultCurrency.icon=icon-ki-coin-omega-gold
walletCommand=wallet
sendPluginWelcome=true
welcomeBonus.enabled=true
welcomeBonus.amount=10

# possible values: OFF,FATAL,ERROR,WARN,INFO,DEBUG,TRACE,ALL
logLevel=ALL
